# Generated by Django 4.0.4 on 2022-05-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тематика')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Слово')),
                ('transcription', models.CharField(max_length=150, verbose_name='Транскрипция')),
                ('translation', models.CharField(max_length=150, verbose_name='Перевод')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='words.topicword', verbose_name='тематики')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
