# Generated by Django 4.0.4 on 2022-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicword',
            name='image',
            field=models.ImageField(upload_to='media/img/', verbose_name='Изображение'),
        ),
    ]
